# yaml-language-server: $schema=./node_modules/envio/fuel.schema.json
name: envio-indexer
ecosystem: fuel
networks:
  - id: 9889
    start_block: 0
    contracts:
      - name: Mira
        address:
          - 0x2e40f2b244b98ed6b8204b3de0156c6961f98525c8162f80162fcf53eebd90e7
        abi_file_path: abis/mainnet/mira-abi.json
        handler: src/EventHandlers.ts
        events:
          - name: MintEvent
          - name: BurnEvent
          - name: CreatePoolEvent
          - name: SwapEvent
      - name: SRC20
        abi_file_path: abis/mainnet/src20-abi.json
        handler: src/token-metadata.ts
        events:
          - name: SetDecimalsEvent
          - name: SetNameEvent
          - name: SetSymbolEvent
raw_events: true
