# yaml-language-server: $schema=./node_modules/envio/fuel.schema.json
name: envio-indexer
ecosystem: fuel
networks:
- id: 0
  start_block: 0
  contracts:
  - name: Mira
    address:
    - 0xd5a716d967a9137222219657d7877bd8c79c64e1edb5de9f2901c98ebe74da80
    abi_file_path: abis/mira-abi.json
    handler: src/EventHandlers.ts
    events:
    - name: MintEvent
      logId: '12547144180067087194'
    - name: BurnEvent
      logId: '3903049024573527731'
    - name: CreatePoolEvent
      logId: '12224862438738316526'
    - name: SwapEvent
      logId: '7938487056892321597'
